# Generated by Django 3.2.2 on 2021-05-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_rename_article_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
